name: Publish Docker image
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Generate Docker tag
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: jdan/hashart/docker
          tags: type=sha,prefix=
      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: jdan/hashart/docker
          tags: ${{ steps.meta.outputs.tags }}
