name: Publish Docker image
on:
  push:
    branches:
      - main
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate Docker tag
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            docker.pkg.github.com/jdan/hashart/hashart-srv
          tags: |
            type=sha,prefix=
            type=raw,value=latest

      - name: Log into GitHub Package registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build and push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
